//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Capa_Entidad;

    public partial class BDPEntities : DbContext
    {
        public BDPEntities()
            : base("name=BDPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cuentas> cuentas { get; set; }
        public virtual DbSet<departamentos> departamentos { get; set; }
        public virtual DbSet<documento> documento { get; set; }
        public virtual DbSet<empleados> empleados { get; set; }
    }
}
