//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Entidad
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class cuentas
    {
        public int id_cuenta { get; set; }
        [DisplayName("Nombre de usuario")]
        [Required]
        public string nombre { get; set; }
        [DisplayName("Correo")]
        [Required]
        public string correo { get; set; }
        [DisplayName("Contraseña")]
        [DataType(DataType.Password)]
        [Required]
        public string pass { get; set; }
    }
}
