//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Entidad
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class departamentos
    {
        public int id_dept { get; set; }
        [DisplayName("Cargo")]
        [Required]
        public string nombre { get; set; }
        [DisplayName("Siglas")]
        [Required]
        public string sigla { get; set; }
    }
}
